security:
    enable_authenticator_manager: true


    providers:
        pimcore_admin:
            id: Pimcore\Security\User\UserProvider

        demo_cms_provider:
            id: Pimcore\Security\User\ObjectUserProvider


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        # Pimcore WebDAV HTTP basic // DO NOT CHANGE!
        pimcore_webdav:
            pattern: ^/asset/webdav
            provider: pimcore_admin
            http_basic: ~

        # Pimcore Admin Bundle firewall
        pimcore_admin: '%pimcore_admin_bundle.firewall_settings%'

        demo_frontend:

            provider: demo_cms_provider

            entry_point: form_login

            custom_authenticators:
                - App\Security\CustomAuthenticator

            form_login:
                enable_csrf: true
                login_path: 'login'
                check_path: 'login'
                default_target_path: 'home'


            logout:
                path: 'logout'
                target: /

                # optional: to keep logins of other firewalls (like admin)
                invalidate_session: false




    access_control:
        # Pimcore admin ACl  // DO NOT CHANGE!
        - { path: ^/admin/settings/display-custom-logo, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login/2fa-verify, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/admin/login/2fa-setup, roles: ROLE_PIMCORE_USER }
        - { path: ^/admin/login/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login/(login|lostpassword|deeplink|csrf-token)$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_PIMCORE_USER }
        - { path: ^/asset/webdav, roles: ROLE_PIMCORE_USER }
        - { path: ^/Pocetna, roles: ROLE_USER}
        - { path: ^/Doktor, roles: ROLE_ADMIN}
        - { path: ^/Pacijenti, roles: ROLE_USER}
        - { path: ^/Profil, roles: ROLE_USER}
        - { path: ^/Kontakt, roles: ROLE_USER}
        - { path: ^/Pregledi, roles: ROLE_USER}


    role_hierarchy:
        # Pimcore admin  // DO NOT CHANGE!
        ROLE_PIMCORE_ADMIN: [ROLE_PIMCORE_USER]
        ROLE_ADMIN: [ROLE_USER]

