_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation


patient_form:
    path: /submit-patient-form
    controller: 'App\Controller\PatientController::submitFormAction'

examination_form:
    path: /submit-examination-form
    controller: 'App\Controller\ExaminationController::examinationActionForm'

doctor_form:
    path: /submit-doctor-form
    controller: 'App\Controller\DoctorController::doctorSubmitAction'

examination_edit:
    path: /Pacijenti/examinationedit/{id}
    controller: 'App\Controller\PatientController::editExaminationsAction'
    methods: [ GET, POST ]

examination_remove:
    path: /Pacijenti/examinationremove/{id}
    controller: 'App\Controller\PatientController::removeExaminationsAction'

patient_class_edit:
    path: /Pacijenti/edit/{id}
    controller: 'App\Controller\PatientController::edit'
    methods: [GET, POST]

patient_remove:
    path: /Pacijenti/remove/{id}
    controller: 'App\Controller\PatientController::remove'

doctor_class_edit:
    path: /Doktori/edit/{id}
    controller: 'App\Controller\DoctorController::edit'
    methods: [GET, POST]

doctor_remove:
    path: /Doktori/remove/{id}
    controller: 'App\Controller\DoctorController::remove'

patient_list:
    path: /Pacijenti
    controller: 'App\Controller\PatientController::listingAction'
    methods: ['GET']

doctors_list:
    path: /Doktori
    controller: 'App\Controller\DoctorController::doctorAction'
    methods: ['GET']

login:
    path: /login
    controller: 'App\Controller\LoginController::loginAction'

register:
    path: /Registracija
    controller: 'App\Controller\RegisterController::registerAction'

Doktori:
    path: /Doktori
    controller: 'App\Controller\DoctorController::doctorAction'

home:
    path: /Pocetna
    controller: 'App\Controller\DefaultController::defaultAction'

logout:
    path: /logout
    controller: 'App\Controller\LoginController::logoutAction'