_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation


patient_form:
    path: /submit-patient-form
    controller: 'App\Controller\PatientController::submitFormAction'

examination_form:
    path: /submit-examination-form
    controller: 'App\Controller\ExaminationController::examinationActionForm'

doctor_form:
    path: /submit-doctor-form
    controller: 'App\Controller\DoctorController::doctorSubmitAction'

patient_class_edit:
    path: /Pacijenti/edit/{id}
    controller: 'App\Controller\PatientController::edit'
    methods: [GET, POST]

patient_remove:
    path: /Pacijenti/remove/{id}
    controller: 'App\Controller\PatientController::remove'

patient_list:
    path: /Pacijenti
    controller: 'App\Controller\PatientController::listingAction'
    methods: ['GET']

Prijava:
    path: /Prijava
    controller: 'App\Controller\LoginController::loginAction'

register:
    path: /Registracija
    controller: 'App\Controller\RegisterController::registerAction'

